version: "3"

services:
  mibreit-c-dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/home/developer/develop
      - ${HOME}/.ssh:/home/developer/.ssh
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - USER=developer
      - UID
